### ISSUE TITLE
Animating sprite sheets

### ISSUE THREAD

**Issue by feelingsonice** [djeedai/bevy_tweening#120]
First of all. Thanks for this repo. I just discovered it and it's really well made and saving me a lot of time.

It feels natural to use this to tick the index of a `TextureAtlas` so I gave it a thought. I'm coming up on some loose ends. Here's what I can gauge:

- Using `Tween` to tick the `TextureAtlas` doesn't feel right since each frame of the index could take varying amounts of time. `Tween` only takes one duration.
- String together `Tween` into `Sequence` is verbose, and loses some of the functionality of `Tween`, such as the ability to repeat the sequence as a whole or sending events on completion.
- It feels natural to use `EaseMethod::Discrete` for this purpose but the value returned by `progress` is exclusive, hence you're limited to doing something like `EaseMethod::Discrete(0.999)`, which isn't that bad but feels hacky. This is what I'm coming up against if I were to choose to implement a custom `Lens`.

Any thoughts on how to use it to tick sprite sheet indices? Is this something you could support?

**Comment by djeedai** [comment]
> since each frame of the index could take varying amounts of time

But you can have an indirection in your custom `Lens` which converts the `Tween`'s linear time into the index of the frame that this time corresponds to, no? I believe you have everything here.

**Comment by djeedai** [comment]
>  Where I'd use the ratio in lerp to determine which frame I'm in. Since Duration::from_millis(600) is twice the duration of the 300ms, this would just be an animation playing at 0.5X the speed?

Yes essentially. Except I think it's more common for each frame to have a duration for which it's visible, than to have what looks like inter-frame durations. But that's a detail, depends on what data you have.

> This is fine except there's now redundancy between the duration given to Tween::new and the set_speed method. A user would need to manually calculate that the duration is 300ms when creating Tween unless they want it sped up.

Well, you're abusing an animation system (tweening) to play an animation of another type (sprite animation). So yes it's not unexpected to have 2 different time references. But you can always make a helper that will create the proper `Tween` given a sprite animation, no?

> This aside, I feel like it would be still helpful to have some of the methods on Tween be implemented for Sequence? Especially completion events/callbacks and repeat strategies.

Yes. Except that as explained on the relevant issue there's a design question about sequence repeat, which more of less boils down to what happens if you put an infinite tween inside a repeatable sequence? Any tween after the infinite one will never play. But then what happens if you seek from end? All those become edge cases with no intrinsic or expected answer. Not that I don't _want_ to have repeatable sequences; I just can't find a single tangible proposal for it which doesn't fall apart when considering those edge cases.

**Comment by djeedai** [comment]
@feelingsonice any more question or concern or this, or can we close this issue? Did you manage to do what you were trying?
